[package]
name = "rs_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
run_script = "0.10.1"
# tauri = { version = "1.3", features = ["shell-open"] }
