[package]
name = "rs_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6.2"
log = "0.4.17"
hifitime = "3.8.2"
lazy-regex = "2.5.0"
thiserror = "1.0.40"
